// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/clear-opfs": {
    params: {};
  };
  "/collections/sqlite-test": {
    params: {};
  };
  "/collections/indexeddb-test": {
    params: {};
  };
  "/collections/indexeddb-migration-test": {
    params: {};
  };
  "/collections/sync-mode-test": {
    params: {};
  };
  "/collections/sqlite-sync-mode-test": {
    params: {};
  };
  "/collections/standalone-test": {
    params: {};
  };
  "/collections/memory-collection-test": {
    params: {};
  };
  "/collections/memory-collection-n-sync-test": {
    params: {};
  };
  "/collections/keyval-collection-test": {
    params: {};
  };
  "/collections/pagination-test": {
    params: {};
  };
  "/collections/sqlite-pagination-test": {
    params: {};
  };
  "/collections/tanstack-06-virtual-props-demo": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/clear-opfs" | "/collections/sqlite-test" | "/collections/indexeddb-test" | "/collections/indexeddb-migration-test" | "/collections/sync-mode-test" | "/collections/sqlite-sync-mode-test" | "/collections/standalone-test" | "/collections/memory-collection-test" | "/collections/memory-collection-n-sync-test" | "/collections/keyval-collection-test" | "/collections/pagination-test" | "/collections/sqlite-pagination-test" | "/collections/tanstack-06-virtual-props-demo";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/api/clear-opfs.tsx": {
    id: "routes/api/clear-opfs";
    page: "/api/clear-opfs";
  };
  "routes/collections/sqlite-test.tsx": {
    id: "routes/collections/sqlite-test";
    page: "/collections/sqlite-test";
  };
  "routes/collections/indexeddb-test.tsx": {
    id: "routes/collections/indexeddb-test";
    page: "/collections/indexeddb-test";
  };
  "routes/collections/indexeddb-migration-test.tsx": {
    id: "routes/collections/indexeddb-migration-test";
    page: "/collections/indexeddb-migration-test";
  };
  "routes/collections/sync-mode-test.tsx": {
    id: "routes/collections/sync-mode-test";
    page: "/collections/sync-mode-test";
  };
  "routes/collections/sqlite-sync-mode-test.tsx": {
    id: "routes/collections/sqlite-sync-mode-test";
    page: "/collections/sqlite-sync-mode-test";
  };
  "routes/collections/standalone-test.tsx": {
    id: "routes/collections/standalone-test";
    page: "/collections/standalone-test";
  };
  "routes/collections/memory-collection-test.tsx": {
    id: "routes/collections/memory-collection-test";
    page: "/collections/memory-collection-test";
  };
  "routes/collections/memory-collection-n-sync-test.tsx": {
    id: "routes/collections/memory-collection-n-sync-test";
    page: "/collections/memory-collection-n-sync-test";
  };
  "routes/collections/keyval-collection-test.tsx": {
    id: "routes/collections/keyval-collection-test";
    page: "/collections/keyval-collection-test";
  };
  "routes/collections/pagination-test.tsx": {
    id: "routes/collections/pagination-test";
    page: "/collections/pagination-test";
  };
  "routes/collections/sqlite-pagination-test.tsx": {
    id: "routes/collections/sqlite-pagination-test";
    page: "/collections/sqlite-pagination-test";
  };
  "routes/collections/tanstack-06-virtual-props-demo.tsx": {
    id: "routes/collections/tanstack-06-virtual-props-demo";
    page: "/collections/tanstack-06-virtual-props-demo";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/api/clear-opfs": typeof import("./app/routes/api/clear-opfs.tsx");
  "routes/collections/sqlite-test": typeof import("./app/routes/collections/sqlite-test.tsx");
  "routes/collections/indexeddb-test": typeof import("./app/routes/collections/indexeddb-test.tsx");
  "routes/collections/indexeddb-migration-test": typeof import("./app/routes/collections/indexeddb-migration-test.tsx");
  "routes/collections/sync-mode-test": typeof import("./app/routes/collections/sync-mode-test.tsx");
  "routes/collections/sqlite-sync-mode-test": typeof import("./app/routes/collections/sqlite-sync-mode-test.tsx");
  "routes/collections/standalone-test": typeof import("./app/routes/collections/standalone-test.tsx");
  "routes/collections/memory-collection-test": typeof import("./app/routes/collections/memory-collection-test.tsx");
  "routes/collections/memory-collection-n-sync-test": typeof import("./app/routes/collections/memory-collection-n-sync-test.tsx");
  "routes/collections/keyval-collection-test": typeof import("./app/routes/collections/keyval-collection-test.tsx");
  "routes/collections/pagination-test": typeof import("./app/routes/collections/pagination-test.tsx");
  "routes/collections/sqlite-pagination-test": typeof import("./app/routes/collections/sqlite-pagination-test.tsx");
  "routes/collections/tanstack-06-virtual-props-demo": typeof import("./app/routes/collections/tanstack-06-virtual-props-demo.tsx");
};