/**
 * Test Worker for routing requests to Durable Objects
 *
 * This worker demonstrates:
 * 1. Using Hono with Cloudflare Workers and DOs
 * 2. Routing pattern for multi-tenant applications (room-based)
 * 3. Forwarding requests to Durable Objects via stubs
 *
 * Reference: https://developers.cloudflare.com/durable-objects/best-practices/accessing-durable-objects-from-a-worker/
 */

import { Hono } from "hono";
import { ChatRoomDO } from "./ChatRoomDO";
import { StandardSchemaChatRoomDO } from "./StandardSchemaChatRoomDO";
import { StandardSchemaChatRoomDO_CustomProtocolError } from "./StandardSchemaChatRoomDO_CustomProtocolError";
import { StandardSchemaChatRoomDO_Dynamic } from "./StandardSchemaChatRoomDO_Dynamic";
import { StandardSchemaChatRoomDO_JSON } from "./StandardSchemaChatRoomDO_JSON";

// Main worker that routes to the Durable Object
// Env type is auto-generated by `wrangler types` from wrangler.jsonc
const app = new Hono<{ Bindings: Env }>();

app.get("/room/:roomId/*", async (c) => {
	const roomId = c.req.param("roomId");

	const stub = c.env.CHAT_ROOM.getByName(roomId);

	const url = new URL(c.req.url);
	const path = url.pathname.replace(`/room/${roomId}`, "");
	url.pathname = path || "/";

	return stub.fetch(new Request(url.toString(), c.req.raw));
});

app.post("/room/:roomId/*", async (c) => {
	const roomId = c.req.param("roomId");
	const stub = c.env.CHAT_ROOM.getByName(roomId);

	const url = new URL(c.req.url);
	const path = url.pathname.replace(`/room/${roomId}`, "");
	url.pathname = path || "/";

	return stub.fetch(new Request(url.toString(), c.req.raw));
});

// StandardSchemaChatRoomDO — buffer messages (msgpack)
app.all("/schema-chat/*", async (c) => {
	const stub = c.env.SCHEMA_CHAT_ROOM.getByName("schema-test-room");

	const url = new URL(c.req.url);
	const path = url.pathname.replace("/schema-chat", "");
	url.pathname = path || "/";

	return stub.fetch(new Request(url.toString(), c.req.raw));
});

// StandardSchemaChatRoomDO_JSON — JSON messages only
app.all("/schema-chat-json/*", async (c) => {
	const stub = c.env.SCHEMA_CHAT_ROOM_JSON.getByName("schema-test-room-json");

	const url = new URL(c.req.url);
	const path = url.pathname.replace("/schema-chat-json", "");
	url.pathname = path || "/";

	return stub.fetch(new Request(url.toString(), c.req.raw));
});

// StandardSchemaChatRoomDO_Dynamic — query param format switching
app.all("/schema-chat-dynamic/*", async (c) => {
	const stub = c.env.SCHEMA_CHAT_ROOM_DYNAMIC.getByName(
		"schema-test-room-dynamic",
	);

	const url = new URL(c.req.url);
	const path = url.pathname.replace("/schema-chat-dynamic", "");
	url.pathname = path || "/";

	return stub.fetch(new Request(url.toString(), c.req.raw));
});

// StandardSchemaChatRoomDO_CustomProtocolError — custom protocol error handling
app.all("/schema-chat-custom-error/*", async (c) => {
	const stub = c.env.SCHEMA_CHAT_ROOM_CUSTOM_ERROR.getByName(
		"schema-test-room-custom-error",
	);

	const url = new URL(c.req.url);
	const path = url.pathname.replace("/schema-chat-custom-error", "");
	url.pathname = path || "/";

	return stub.fetch(new Request(url.toString(), c.req.raw));
});

app.get("/", (c) => {
	return c.text("WebSocket DO Test Worker");
});

export default app;

export {
	ChatRoomDO,
	StandardSchemaChatRoomDO,
	StandardSchemaChatRoomDO_CustomProtocolError,
	StandardSchemaChatRoomDO_Dynamic,
	StandardSchemaChatRoomDO_JSON,
};
