// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/router-toolkit/loader-test": {
    params: {};
  };
  "/router-toolkit/action-test": {
    params: {};
  };
  "/router-toolkit/form-action-test": {
    params: {};
  };
  "/router-toolkit/form-action-unmount-test": {
    params: {};
  };
  "/router-toolkit/key-suffix-dual-submitter-test": {
    params: {};
  };
  "/router-toolkit/shared-fetcher-key-dual-submitter-test": {
    params: {};
  };
  "/router-toolkit/concurrent-submitter-test": {
    params: {};
  };
  "/router-toolkit/plain-json-action-test": {
    params: {};
  };
  "/router-toolkit/submitter-with-loader": {
    params: {};
  };
  "/router-toolkit/fetcher-data-refresh": {
    params: {};
  };
  "/router-toolkit/fetcher-invalidation": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/router-toolkit/loader-test" | "/router-toolkit/action-test" | "/router-toolkit/form-action-test" | "/router-toolkit/form-action-unmount-test" | "/router-toolkit/key-suffix-dual-submitter-test" | "/router-toolkit/shared-fetcher-key-dual-submitter-test" | "/router-toolkit/concurrent-submitter-test" | "/router-toolkit/plain-json-action-test" | "/router-toolkit/submitter-with-loader" | "/router-toolkit/fetcher-data-refresh" | "/router-toolkit/fetcher-invalidation";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/router-toolkit/loader-test.tsx": {
    id: "routes/router-toolkit/loader-test";
    page: "/router-toolkit/loader-test";
  };
  "routes/router-toolkit/action-test.tsx": {
    id: "routes/router-toolkit/action-test";
    page: "/router-toolkit/action-test";
  };
  "routes/router-toolkit/form-action-test.tsx": {
    id: "routes/router-toolkit/form-action-test";
    page: "/router-toolkit/form-action-test";
  };
  "routes/router-toolkit/form-action-unmount-test.tsx": {
    id: "routes/router-toolkit/form-action-unmount-test";
    page: "/router-toolkit/form-action-unmount-test";
  };
  "routes/router-toolkit/key-suffix-dual-submitter-test.tsx": {
    id: "routes/router-toolkit/key-suffix-dual-submitter-test";
    page: "/router-toolkit/key-suffix-dual-submitter-test";
  };
  "routes/router-toolkit/shared-fetcher-key-dual-submitter-test.tsx": {
    id: "routes/router-toolkit/shared-fetcher-key-dual-submitter-test";
    page: "/router-toolkit/shared-fetcher-key-dual-submitter-test";
  };
  "routes/router-toolkit/concurrent-submitter-test.tsx": {
    id: "routes/router-toolkit/concurrent-submitter-test";
    page: "/router-toolkit/concurrent-submitter-test";
  };
  "routes/router-toolkit/plain-json-action-test.tsx": {
    id: "routes/router-toolkit/plain-json-action-test";
    page: "/router-toolkit/plain-json-action-test";
  };
  "routes/router-toolkit/submitter-with-loader.tsx": {
    id: "routes/router-toolkit/submitter-with-loader";
    page: "/router-toolkit/submitter-with-loader";
  };
  "routes/router-toolkit/fetcher-data-refresh.tsx": {
    id: "routes/router-toolkit/fetcher-data-refresh";
    page: "/router-toolkit/fetcher-data-refresh";
  };
  "routes/router-toolkit/fetcher-invalidation.tsx": {
    id: "routes/router-toolkit/fetcher-invalidation";
    page: "/router-toolkit/fetcher-invalidation";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/router-toolkit/loader-test": typeof import("./app/routes/router-toolkit/loader-test.tsx");
  "routes/router-toolkit/action-test": typeof import("./app/routes/router-toolkit/action-test.tsx");
  "routes/router-toolkit/form-action-test": typeof import("./app/routes/router-toolkit/form-action-test.tsx");
  "routes/router-toolkit/form-action-unmount-test": typeof import("./app/routes/router-toolkit/form-action-unmount-test.tsx");
  "routes/router-toolkit/key-suffix-dual-submitter-test": typeof import("./app/routes/router-toolkit/key-suffix-dual-submitter-test.tsx");
  "routes/router-toolkit/shared-fetcher-key-dual-submitter-test": typeof import("./app/routes/router-toolkit/shared-fetcher-key-dual-submitter-test.tsx");
  "routes/router-toolkit/concurrent-submitter-test": typeof import("./app/routes/router-toolkit/concurrent-submitter-test.tsx");
  "routes/router-toolkit/plain-json-action-test": typeof import("./app/routes/router-toolkit/plain-json-action-test.tsx");
  "routes/router-toolkit/submitter-with-loader": typeof import("./app/routes/router-toolkit/submitter-with-loader.tsx");
  "routes/router-toolkit/fetcher-data-refresh": typeof import("./app/routes/router-toolkit/fetcher-data-refresh.tsx");
  "routes/router-toolkit/fetcher-invalidation": typeof import("./app/routes/router-toolkit/fetcher-invalidation.tsx");
};