/**
 * Test Worker for ChatAgent Durable Objects
 *
 * This worker is used for chat-agent E2E tests with Playwright.
 * It routes requests to the TestChatAgent Durable Object.
 *
 * Reference: https://developers.cloudflare.com/durable-objects/best-practices/access-durable-objects-from-a-worker/
 */

import { Hono } from "hono";
import { TestChatAgent } from "./TestChatAgent";

// Main worker that routes to the ChatAgent Durable Object
// Env type is auto-generated by `wrangler types` from wrangler.jsonc
const app = new Hono<{ Bindings: Env }>();

app.all("/chat-agent/:agentId/*", async (c) => {
	const agentId = c.req.param("agentId");
	const stub = c.env.TEST_CHAT_AGENT.getByName(agentId);

	const url = new URL(c.req.url);
	const path = url.pathname.replace(`/chat-agent/${agentId}`, "");
	url.pathname = path || "/";

	// Clone the request and add required PartyServer headers
	const headers = new Headers(c.req.raw.headers);
	headers.set("x-partykit-room", agentId);

	return stub.fetch(
		new Request(url.toString(), {
			method: c.req.method,
			headers,
			body: c.req.raw.body,
			duplex: "half",
		}),
	);
});

app.get("/", (c) => {
	return c.text("ChatAgent E2E Test Worker");
});

// Test endpoint to check environment variables
app.get("/env-status", (c) => {
	return c.json({
		hasOpenRouterKey: !!c.env.OPENROUTER_API_KEY,
		hasAccountId: !!c.env.CLOUDFLARE_ACCOUNT_ID,
		hasGatewayName: !!c.env.AI_GATEWAY_NAME,
		hasGatewayToken: !!c.env.AI_GATEWAY_TOKEN,
	});
});

export default app;

// IMPORTANT: Must export DO class for wrangler to bind it
// The class_name in wrangler.jsonc refers to this exported name
// Reference: https://developers.cloudflare.com/durable-objects/get-started/#durable-object-class
export { TestChatAgent };
