// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/grid": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/grid";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/grid.tsx": {
    id: "routes/grid";
    page: "/grid";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/grid": typeof import("./app/routes/grid.tsx");
};